apiVersion: v1
kind: Pod
metadata:
  name: vishaal-sklearn
spec:
  restartPolicy: Never
  containers:
  - name: vishaal-sklearn
    image: crdsba6190deveastus001.azurecr.io/vishaal-sklearn:latest
    volumeMounts:
      - name: datalake
        mountPath: "/mnt/datalake/"
        readOnly: false
    # command: ["/bin/bash", "-c"]
    # args: ["./run.py"]
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    # resources:
    #   limits:
    #     memory: "2Gi"
    #     cpu: "200m"
  imagePullSecrets:
    - name: acr-secret
  volumes:
    - name: datalake
      persistentVolumeClaim:
        claimName: pvc-datalake-class-blob